[tool.poetry]
name = "viser"
version = "0.0.0"
description = "3D visualization helper"
authors = ["brentyi <brentyi@berkeley.edu>"]
include = ["./viser/**/*"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
websockets = "^10.4"
trimesh = "^3.21.0"
numpy = "^1.24.2"
msgpack = "^1.0.5"
imageio = "^2.26.1"
pyliblzfse = "^0.4.1"
scikit-image = "^0.20.0"
tqdm = "^4.65.0"
tyro = "^0.4.2"
gdown = "^4.6.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true
warn_unused_configs = true
